Feat: added Line.project_points, Line.distance_points, Plane.project_…
ajhynes7/scikit-spatial pull request #347
Opened 2024-01-29 18:32 UTC by EdYazbec

…points, Plane.distance_points, Plane.distance_points_signed, and matching tests

Docs: added new features to README.rst

This is functionality that I use a lot. My tests check that the new functions return the same result as the existing functions.

2024-01-30 20:43 UTC, CristianoPizzamiglio approved these changes
I think these are very useful methods. As far as I am concerned, I often have to project `Points` on a plane so I will definitely use the `project_points` method.
The code seems to be very clean to me and in line with the codebase's coding style.

2024-01-30 20:56 UTC, ajhynes7 requested changes
Hi @EdYazbec,

I agree with Cristiano that the code and docstrings maintain the style of the project, so thanks for paying attention to that!

I have a few suggested edits for the text, and some other comments.

2024-01-30 20:56 UTC, ajhynes7 commented on README.rst
> +
This shouldn't be added to the README. If you're explaining the purpose of this branch, it should go in the PR description instead.

2024-01-30 20:56 UTC, ajhynes7 commented on src/skspatial/objects/line.py
> +        Project points onto the line.
```suggestion
        Project multiple points onto the line.
```

2024-01-30 20:56 UTC, ajhynes7 commented on src/skspatial/objects/line.py
> +        Return the distance from points to the line.
```suggestion
        Return the distances from multiple points to the line.
```

2024-01-30 20:56 UTC, ajhynes7 commented on src/skspatial/objects/line.py
> +        This is the distance from points to their projection on the line.
```suggestion
        These are the distances from the points to their projections on the line.
```

2024-01-30 20:56 UTC, ajhynes7 commented on src/skspatial/objects/line.py
> +            Distances from the point to the line.
```suggestion
            Distances from the points to the line.
```

2024-01-30 20:56 UTC, ajhynes7 commented on src/skspatial/objects/plane.py
> +        Project points onto the plane.
```suggestion
        Project multiple points onto the plane.
```

2024-01-30 20:56 UTC, ajhynes7 commented on src/skspatial/objects/plane.py
> +            Projection of the points onto the plane.
```suggestion
            Projections of the points onto the plane.
```

2024-01-30 20:56 UTC, ajhynes7 commented on src/skspatial/objects/plane.py
> +        Return the signed distances from points to the plane.
```suggestion
        Return the signed distances from multiple points to the plane.
```

2024-01-30 20:56 UTC, ajhynes7 commented on src/skspatial/objects/plane.py
> +        Return the distances from points to the plane.
```suggestion
        Return the distances from multiple points to the plane.
```

2024-01-30 20:56 UTC, ajhynes7 commented on tests/unit/objects/test_line.py
> +    assert np.all(np.isclose(points_projected, points_expected))
I think `np.allclose` would be more appropriate to use here.

2024-02-09 15:12 UTC, EdYazbec commented
Thanks for your feedback! I'll get these implemented and go from there.

2024-02-10 16:45 UTC, ajhynes7 commented on src/skspatial/objects/plane.py
> +            Input point.
```suggestion
            Input points.
```

2024-02-10 16:50 UTC, ajhynes7 requested changes

2024-02-10 16:50 UTC, ajhynes7 commented on tests/unit/objects/test_line.py
> +    distanecs_expected = [line.distance_point(point) for point in points]
```suggestion
    distances_expected = [line.distance_point(point) for point in points]
```

2024-02-10 16:50 UTC, ajhynes7 commented on tests/unit/objects/test_line.py
> +    distanecs_expected = [line.distance_point(point) for point in array_points]
```suggestion
    distances_expected = [line.distance_point(point) for point in array_points]
```

2024-02-10 16:50 UTC, ajhynes7 commented on tests/unit/objects/test_plane.py
> +    distances_expected = [plane.distance_points(point) for point in points]
```suggestion
    distances_expected = [plane.distance_point(point) for point in points]
```

2024-02-10 16:50 UTC, ajhynes7 commented on tests/unit/objects/test_plane.py
> +    distanecs_expected = [plane.distance_point(point) for point in points]
```suggestion
    distances_expected = [plane.distance_point(point) for point in points]
```

2024-02-10 16:50 UTC, ajhynes7 commented on tests/unit/objects/test_plane.py
> +    distances_signed_expected = [plane.distance_points_signed(point) for point in points]
```suggestion
    distances_signed_expected = [plane.distance_point_signed(point) for point in points]
```

2024-02-10 16:50 UTC, ajhynes7 commented on tests/unit/objects/test_plane.py
> +    assert np.allclose(distances, distanecs_expected)
```suggestion
    assert np.allclose(distances, distances_expected)
```

2024-02-10 17:10 UTC, ajhynes7 commented on tests/unit/objects/test_line.py
> +    assert np.allclose(distances, distanecs_expected)
```suggestion
    assert np.allclose(distances, distances_expected)
```

2024-02-10 17:11 UTC, ajhynes7 commented on tests/unit/objects/test_line.py
> +    assert np.allclose(distances, distanecs_expected)
```suggestion
    assert np.allclose(distances, distances_expected)
```

2024-02-10 17:20 UTC, ajhynes7 commented
Looks good! Thanks for contributing these. I'll get a release out soon.

2024-02-10 17:20 UTC, merged